//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDrinkzy.DrinkServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuperAlchohol", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfDrinkzy.DrinkServiceRef.Alchohol))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfDrinkzy.DrinkServiceRef.HelFlask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfDrinkzy.DrinkServiceRef.Drink))]
    public partial class SuperAlchohol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Img {
            get {
                return this.ImgField;
            }
            set {
                if ((object.ReferenceEquals(this.ImgField, value) != true)) {
                    this.ImgField = value;
                    this.RaisePropertyChanged("Img");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alchohol", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    [System.SerializableAttribute()]
    public partial class Alchohol : WpfDrinkzy.DrinkServiceRef.SuperAlchohol {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProcentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Procent {
            get {
                return this.ProcentField;
            }
            set {
                if ((this.ProcentField.Equals(value) != true)) {
                    this.ProcentField = value;
                    this.RaisePropertyChanged("Procent");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HelFlask", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    [System.SerializableAttribute()]
    public partial class HelFlask : WpfDrinkzy.DrinkServiceRef.SuperAlchohol {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProcentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Procent {
            get {
                return this.ProcentField;
            }
            set {
                if ((this.ProcentField.Equals(value) != true)) {
                    this.ProcentField = value;
                    this.RaisePropertyChanged("Procent");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Drink", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    [System.SerializableAttribute()]
    public partial class Drink : WpfDrinkzy.DrinkServiceRef.SuperAlchohol {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfDrinkzy.DrinkServiceRef.Ingredient[] IngredientsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfDrinkzy.DrinkServiceRef.Ingredient[] Ingredients {
            get {
                return this.IngredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.IngredientsField, value) != true)) {
                    this.IngredientsField = value;
                    this.RaisePropertyChanged("Ingredients");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ingredient", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    [System.SerializableAttribute()]
    public partial class Ingredient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProcentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Procent {
            get {
                return this.ProcentField;
            }
            set {
                if ((this.ProcentField.Equals(value) != true)) {
                    this.ProcentField = value;
                    this.RaisePropertyChanged("Procent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DrinkServiceRef.IDrinkService")]
    public interface IDrinkService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/CreateDrink", ReplyAction="http://tempuri.org/IDrinkService/CreateDrinkResponse")]
        void CreateDrink(WpfDrinkzy.DrinkServiceRef.Drink drink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/CreateDrink", ReplyAction="http://tempuri.org/IDrinkService/CreateDrinkResponse")]
        System.Threading.Tasks.Task CreateDrinkAsync(WpfDrinkzy.DrinkServiceRef.Drink drink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/GetDrink", ReplyAction="http://tempuri.org/IDrinkService/GetDrinkResponse")]
        WpfDrinkzy.DrinkServiceRef.Drink GetDrink(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/GetDrink", ReplyAction="http://tempuri.org/IDrinkService/GetDrinkResponse")]
        System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Drink> GetDrinkAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/getAllDrinks", ReplyAction="http://tempuri.org/IDrinkService/getAllDrinksResponse")]
        WpfDrinkzy.DrinkServiceRef.Drink[] getAllDrinks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/getAllDrinks", ReplyAction="http://tempuri.org/IDrinkService/getAllDrinksResponse")]
        System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Drink[]> getAllDrinksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/UpdateDrink", ReplyAction="http://tempuri.org/IDrinkService/UpdateDrinkResponse")]
        void UpdateDrink(WpfDrinkzy.DrinkServiceRef.Drink drink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/UpdateDrink", ReplyAction="http://tempuri.org/IDrinkService/UpdateDrinkResponse")]
        System.Threading.Tasks.Task UpdateDrinkAsync(WpfDrinkzy.DrinkServiceRef.Drink drink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/DeleteDrinkById", ReplyAction="http://tempuri.org/IDrinkService/DeleteDrinkByIdResponse")]
        void DeleteDrinkById(int DrinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/DeleteDrinkById", ReplyAction="http://tempuri.org/IDrinkService/DeleteDrinkByIdResponse")]
        System.Threading.Tasks.Task DeleteDrinkByIdAsync(int DrinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/AddIngredientToDrink", ReplyAction="http://tempuri.org/IDrinkService/AddIngredientToDrinkResponse")]
        void AddIngredientToDrink(int ingredientID, WpfDrinkzy.DrinkServiceRef.Drink drink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/AddIngredientToDrink", ReplyAction="http://tempuri.org/IDrinkService/AddIngredientToDrinkResponse")]
        System.Threading.Tasks.Task AddIngredientToDrinkAsync(int ingredientID, WpfDrinkzy.DrinkServiceRef.Drink drink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/DeleteIngredientFromDrink", ReplyAction="http://tempuri.org/IDrinkService/DeleteIngredientFromDrinkResponse")]
        void DeleteIngredientFromDrink(int ingredientID, WpfDrinkzy.DrinkServiceRef.Drink drink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/DeleteIngredientFromDrink", ReplyAction="http://tempuri.org/IDrinkService/DeleteIngredientFromDrinkResponse")]
        System.Threading.Tasks.Task DeleteIngredientFromDrinkAsync(int ingredientID, WpfDrinkzy.DrinkServiceRef.Drink drink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/SearchDrinks", ReplyAction="http://tempuri.org/IDrinkService/SearchDrinksResponse")]
        WpfDrinkzy.DrinkServiceRef.Drink[] SearchDrinks(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/SearchDrinks", ReplyAction="http://tempuri.org/IDrinkService/SearchDrinksResponse")]
        System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Drink[]> SearchDrinksAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/CreateAlchohol", ReplyAction="http://tempuri.org/IDrinkService/CreateAlchoholResponse")]
        void CreateAlchohol(WpfDrinkzy.DrinkServiceRef.Alchohol alchohol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/CreateAlchohol", ReplyAction="http://tempuri.org/IDrinkService/CreateAlchoholResponse")]
        System.Threading.Tasks.Task CreateAlchoholAsync(WpfDrinkzy.DrinkServiceRef.Alchohol alchohol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/GetAlchohol", ReplyAction="http://tempuri.org/IDrinkService/GetAlchoholResponse")]
        WpfDrinkzy.DrinkServiceRef.Alchohol GetAlchohol(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/GetAlchohol", ReplyAction="http://tempuri.org/IDrinkService/GetAlchoholResponse")]
        System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Alchohol> GetAlchoholAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/GetAllAlchohols", ReplyAction="http://tempuri.org/IDrinkService/GetAllAlchoholsResponse")]
        WpfDrinkzy.DrinkServiceRef.Alchohol[] GetAllAlchohols();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/GetAllAlchohols", ReplyAction="http://tempuri.org/IDrinkService/GetAllAlchoholsResponse")]
        System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Alchohol[]> GetAllAlchoholsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/GetHelflask", ReplyAction="http://tempuri.org/IDrinkService/GetHelflaskResponse")]
        WpfDrinkzy.DrinkServiceRef.HelFlask GetHelflask(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/GetHelflask", ReplyAction="http://tempuri.org/IDrinkService/GetHelflaskResponse")]
        System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.HelFlask> GetHelflaskAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/searchHelflask", ReplyAction="http://tempuri.org/IDrinkService/searchHelflaskResponse")]
        WpfDrinkzy.DrinkServiceRef.HelFlask[] searchHelflask(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/searchHelflask", ReplyAction="http://tempuri.org/IDrinkService/searchHelflaskResponse")]
        System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.HelFlask[]> searchHelflaskAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/searchAlchohol", ReplyAction="http://tempuri.org/IDrinkService/searchAlchoholResponse")]
        WpfDrinkzy.DrinkServiceRef.Alchohol[] searchAlchohol(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrinkService/searchAlchohol", ReplyAction="http://tempuri.org/IDrinkService/searchAlchoholResponse")]
        System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Alchohol[]> searchAlchoholAsync(string search);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDrinkServiceChannel : WpfDrinkzy.DrinkServiceRef.IDrinkService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DrinkServiceClient : System.ServiceModel.ClientBase<WpfDrinkzy.DrinkServiceRef.IDrinkService>, WpfDrinkzy.DrinkServiceRef.IDrinkService {
        
        public DrinkServiceClient() {
        }
        
        public DrinkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DrinkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DrinkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DrinkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateDrink(WpfDrinkzy.DrinkServiceRef.Drink drink) {
            base.Channel.CreateDrink(drink);
        }
        
        public System.Threading.Tasks.Task CreateDrinkAsync(WpfDrinkzy.DrinkServiceRef.Drink drink) {
            return base.Channel.CreateDrinkAsync(drink);
        }
        
        public WpfDrinkzy.DrinkServiceRef.Drink GetDrink(int id) {
            return base.Channel.GetDrink(id);
        }
        
        public System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Drink> GetDrinkAsync(int id) {
            return base.Channel.GetDrinkAsync(id);
        }
        
        public WpfDrinkzy.DrinkServiceRef.Drink[] getAllDrinks() {
            return base.Channel.getAllDrinks();
        }
        
        public System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Drink[]> getAllDrinksAsync() {
            return base.Channel.getAllDrinksAsync();
        }
        
        public void UpdateDrink(WpfDrinkzy.DrinkServiceRef.Drink drink) {
            base.Channel.UpdateDrink(drink);
        }
        
        public System.Threading.Tasks.Task UpdateDrinkAsync(WpfDrinkzy.DrinkServiceRef.Drink drink) {
            return base.Channel.UpdateDrinkAsync(drink);
        }
        
        public void DeleteDrinkById(int DrinkId) {
            base.Channel.DeleteDrinkById(DrinkId);
        }
        
        public System.Threading.Tasks.Task DeleteDrinkByIdAsync(int DrinkId) {
            return base.Channel.DeleteDrinkByIdAsync(DrinkId);
        }
        
        public void AddIngredientToDrink(int ingredientID, WpfDrinkzy.DrinkServiceRef.Drink drink) {
            base.Channel.AddIngredientToDrink(ingredientID, drink);
        }
        
        public System.Threading.Tasks.Task AddIngredientToDrinkAsync(int ingredientID, WpfDrinkzy.DrinkServiceRef.Drink drink) {
            return base.Channel.AddIngredientToDrinkAsync(ingredientID, drink);
        }
        
        public void DeleteIngredientFromDrink(int ingredientID, WpfDrinkzy.DrinkServiceRef.Drink drink) {
            base.Channel.DeleteIngredientFromDrink(ingredientID, drink);
        }
        
        public System.Threading.Tasks.Task DeleteIngredientFromDrinkAsync(int ingredientID, WpfDrinkzy.DrinkServiceRef.Drink drink) {
            return base.Channel.DeleteIngredientFromDrinkAsync(ingredientID, drink);
        }
        
        public WpfDrinkzy.DrinkServiceRef.Drink[] SearchDrinks(string search) {
            return base.Channel.SearchDrinks(search);
        }
        
        public System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Drink[]> SearchDrinksAsync(string search) {
            return base.Channel.SearchDrinksAsync(search);
        }
        
        public void CreateAlchohol(WpfDrinkzy.DrinkServiceRef.Alchohol alchohol) {
            base.Channel.CreateAlchohol(alchohol);
        }
        
        public System.Threading.Tasks.Task CreateAlchoholAsync(WpfDrinkzy.DrinkServiceRef.Alchohol alchohol) {
            return base.Channel.CreateAlchoholAsync(alchohol);
        }
        
        public WpfDrinkzy.DrinkServiceRef.Alchohol GetAlchohol(int id) {
            return base.Channel.GetAlchohol(id);
        }
        
        public System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Alchohol> GetAlchoholAsync(int id) {
            return base.Channel.GetAlchoholAsync(id);
        }
        
        public WpfDrinkzy.DrinkServiceRef.Alchohol[] GetAllAlchohols() {
            return base.Channel.GetAllAlchohols();
        }
        
        public System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Alchohol[]> GetAllAlchoholsAsync() {
            return base.Channel.GetAllAlchoholsAsync();
        }
        
        public WpfDrinkzy.DrinkServiceRef.HelFlask GetHelflask(int id) {
            return base.Channel.GetHelflask(id);
        }
        
        public System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.HelFlask> GetHelflaskAsync(int id) {
            return base.Channel.GetHelflaskAsync(id);
        }
        
        public WpfDrinkzy.DrinkServiceRef.HelFlask[] searchHelflask(string search) {
            return base.Channel.searchHelflask(search);
        }
        
        public System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.HelFlask[]> searchHelflaskAsync(string search) {
            return base.Channel.searchHelflaskAsync(search);
        }
        
        public WpfDrinkzy.DrinkServiceRef.Alchohol[] searchAlchohol(string search) {
            return base.Channel.searchAlchohol(search);
        }
        
        public System.Threading.Tasks.Task<WpfDrinkzy.DrinkServiceRef.Alchohol[]> searchAlchoholAsync(string search) {
            return base.Channel.searchAlchoholAsync(search);
        }
    }
}
